export const typeAction = {
    // auth:
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    LOGOUT: 'LOGOUT',

    GET_USERS: 'GET_USERS',

    //post api
    GET_POSTS_PER_USER: 'GET_POSTS_PER_USER',
    GET_ALBUMS_PER_UER: 'GET_ALBUMS_PER_UER',
    SET_USER_OF_POSTS: 'SET_USER_OF_POSTS',

    //comment api
    GET_COMMENTS: 'GET_COMMENTS',
    POST_COMMENT: 'POST_COMMENT',
    PATCH_COMMENT: 'PATCH_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',

    // status
    ERROR: 'ERROR',
    SUCCESS: 'SUCCESS'
}
